apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
        - name: vprodb
          image: containerizingproject/vprofiledb:V1
          args :
            - "--ignore-db-dir=host+found"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
          ports:
            - name: vprodb-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-pass
                  name: app-secret
      nodeSelector:
        zone: us-east-2a
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-00a45feb6d7c75089
            fsType: ext4
